include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=fortune

fortune_C_FILES = \
   fortune.c \
   regexpr.c

fortune_CFLAGS =

fortune_LDFLAGS =

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
